//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/InputSystem/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""MapNormale"",
            ""id"": ""6270f5a0-d32a-4e05-bb6b-efc948f8ed42"",
            ""actions"": [
                {
                    ""name"": ""Mouvement"",
                    ""type"": ""Value"",
                    ""id"": ""0ab0161d-48a6-4a94-8945-9f7120f27341"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Regarder"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f1d3fa08-8b16-4e50-bc50-d4ce285d7440"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Saut"",
                    ""type"": ""Button"",
                    ""id"": ""8583c78a-9671-4e56-bb9f-4b7a573340cc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""957a0511-2a29-4a17-9c0f-3f3fc62d4bea"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LightAttack"",
                    ""type"": ""Button"",
                    ""id"": ""5d7ff4fb-188f-4f3a-a9ca-45144ec65cc3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HeavyAttack"",
                    ""type"": ""Button"",
                    ""id"": ""ee8c3487-baf6-4461-bb07-03a73b651da0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""b79bd28b-b1e2-4315-9194-e8c5de3fa082"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Unsheath"",
                    ""type"": ""Button"",
                    ""id"": ""b227df45-a5f3-408c-adcc-e4386f1d9ef1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LockOn"",
                    ""type"": ""Button"",
                    ""id"": ""0fcb6e4b-1a32-4e44-af23-74b2cd6bcafc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Guarding"",
                    ""type"": ""Button"",
                    ""id"": ""9868ea1a-a7b9-4c70-87f5-dca8b40419e2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Roll"",
                    ""type"": ""Button"",
                    ""id"": ""b0ac6e6b-4762-4b16-9fc6-a85a0a2d84bb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""a0060527-6d40-431d-af1b-7e8d75187783"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heal"",
                    ""type"": ""Button"",
                    ""id"": ""c162b2f7-80fd-4556-9765-a252640e10ad"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LockOnIndexR2"",
                    ""type"": ""Button"",
                    ""id"": ""6ed4c227-6b43-4313-9651-5247c87bf2a9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugTool"",
                    ""type"": ""Button"",
                    ""id"": ""ad88fe52-fb04-4ec9-b325-ca8e5c5ebf34"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchKatana"",
                    ""type"": ""Button"",
                    ""id"": ""3bdffc2f-1855-4bc9-a2a0-61d2a7b8e28c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""0b4b520b-ea1e-4a54-909b-ce587c661788"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouvement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6bec4b5b-0f4a-4f5b-8f6d-5e0bf70bfe11"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Mouvement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""03486e1b-7f69-4b3b-9f7f-a1f338d681b6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Mouvement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9d7a0b5d-e8d1-4750-a593-275555f841c0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Mouvement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a381fb54-756f-4abd-9b8b-9ba41a892f72"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Mouvement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9504cdc4-968e-4d18-9635-3c6d93202e6b"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": "";Controller"",
                    ""action"": ""Mouvement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23452315-0e21-4479-a04b-5fa776146542"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Regarder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fcccf6d-446a-4213-a739-7725b06f6c11"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Regarder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2f45832-fd0a-48d3-88fd-88417e161dad"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82f15c13-619c-403d-af85-f39b435d4f8f"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3adb01de-74cc-4006-9e6c-3a10259b2324"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""LightAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cd19a1a-148b-4278-9bf8-ca4cb072f132"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""LightAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac28b027-17b4-48d4-b37a-b0dce325cea2"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""HeavyAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57810a3e-b7bd-40ff-995e-592280890f74"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""HeavyAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80c07d57-f828-446d-8575-294397f7ebee"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e1d18b6-37af-4339-b13f-be0b920cb25e"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""848abd73-4288-4ca8-b618-5f0c37cfef7d"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Unsheath"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05bbcab9-cc89-4dc5-b133-a48a07d709d5"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Unsheath"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e85acc75-6b92-4246-9d5a-7c1d8f8ceae1"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""LockOn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3f5711c-9c5e-4660-8a7e-9d916cce6780"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""LockOn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f872c9fd-89f8-4802-b2aa-98dae16fdbae"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Guarding"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0b15680-2eca-49fc-aa8e-8811dd4d9b24"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Guarding"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4df1e8b-786b-4484-af84-b7495f7941a2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""088ea887-0e49-4209-aeb4-c9185f6b83a5"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""deb99e2c-89bc-4f7b-b4c5-aa53ff13f5d6"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e89ca49d-a498-4e62-a8c9-f7aad81ce179"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92fe7f6c-a036-416c-841b-7963cd0cc265"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27a6919f-b56d-4ae3-a14d-5c3d7aaa45d2"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""daa7db7a-4cb1-4d91-83da-73592af3474e"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""LockOnIndexR2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ebac36d2-feae-4aa2-b82e-fbb6f4058427"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""LockOnIndexR2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83ece114-5483-464d-b02e-f62db4f39244"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fb1b16f-5242-4105-9924-404d1722afcb"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2dd8fd9d-c901-4cf0-8dba-f9bb8d11726c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""SwitchKatana"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd566198-a9a7-4e99-b120-6441bb8c7973"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""SwitchKatana"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UImap"",
            ""id"": ""3dfb6b9d-8feb-4d93-9ab7-85d0cbc18b51"",
            ""actions"": [
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""29c1ca5d-4906-4df2-9da1-03769fe508ac"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""6664dbd4-45e7-48f8-b2bd-e7eb7067777f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""98fd5be4-90c4-4147-87e3-705196b1b30e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""f9f20c12-a54f-4046-8935-2cc164c1838e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Exit"",
                    ""type"": ""Button"",
                    ""id"": ""6983ec9d-4624-440b-bd2c-fcd6befc2452"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""0446a5de-3f81-4f76-ad4e-6d8db346c8d1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""eed1c20e-c63a-4418-afc1-55c9428f80e4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c70a9ccc-fa74-40e8-b3ff-f0313fc6bc38"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1519cda-78a3-43dd-a94b-bf394d91b795"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca1332cc-c6e0-4e27-aa96-424e8eb47305"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d98128d-9279-419f-bf7a-b27b1c489c7b"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3086a15-e958-41ac-88eb-5dd28bbbc09f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98a2abf4-5d54-4251-879c-1061ed6ecf8e"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""812d4acc-c119-4bbc-bb52-a4e85cfdb28d"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff1aa684-c7a0-4925-9a93-19d20288d88a"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65cec4d3-84a3-4780-86fc-c300a8fb8290"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ab4487c-825d-48a4-9fa7-64d3af27a87c"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff651406-5b4d-4c75-97f8-5e7da6aa4af0"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2804e12c-dbb5-4c9d-b352-90e27036b184"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31dffed4-6e6c-401c-a00d-99146a7abd0b"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b75c1b99-ced1-4057-8e0d-d18e6b4a44e4"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e0ec629-12c8-4fd5-8bf3-e158547dec50"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Controller"",
            ""bindingGroup"": ""Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // MapNormale
        m_MapNormale = asset.FindActionMap("MapNormale", throwIfNotFound: true);
        m_MapNormale_Mouvement = m_MapNormale.FindAction("Mouvement", throwIfNotFound: true);
        m_MapNormale_Regarder = m_MapNormale.FindAction("Regarder", throwIfNotFound: true);
        m_MapNormale_Saut = m_MapNormale.FindAction("Saut", throwIfNotFound: true);
        m_MapNormale_Sprint = m_MapNormale.FindAction("Sprint", throwIfNotFound: true);
        m_MapNormale_LightAttack = m_MapNormale.FindAction("LightAttack", throwIfNotFound: true);
        m_MapNormale_HeavyAttack = m_MapNormale.FindAction("HeavyAttack", throwIfNotFound: true);
        m_MapNormale_Crouch = m_MapNormale.FindAction("Crouch", throwIfNotFound: true);
        m_MapNormale_Unsheath = m_MapNormale.FindAction("Unsheath", throwIfNotFound: true);
        m_MapNormale_LockOn = m_MapNormale.FindAction("LockOn", throwIfNotFound: true);
        m_MapNormale_Guarding = m_MapNormale.FindAction("Guarding", throwIfNotFound: true);
        m_MapNormale_Roll = m_MapNormale.FindAction("Roll", throwIfNotFound: true);
        m_MapNormale_Interact = m_MapNormale.FindAction("Interact", throwIfNotFound: true);
        m_MapNormale_Heal = m_MapNormale.FindAction("Heal", throwIfNotFound: true);
        m_MapNormale_LockOnIndexR2 = m_MapNormale.FindAction("LockOnIndexR2", throwIfNotFound: true);
        m_MapNormale_DebugTool = m_MapNormale.FindAction("DebugTool", throwIfNotFound: true);
        m_MapNormale_SwitchKatana = m_MapNormale.FindAction("SwitchKatana", throwIfNotFound: true);
        // UImap
        m_UImap = asset.FindActionMap("UImap", throwIfNotFound: true);
        m_UImap_Up = m_UImap.FindAction("Up", throwIfNotFound: true);
        m_UImap_Down = m_UImap.FindAction("Down", throwIfNotFound: true);
        m_UImap_Back = m_UImap.FindAction("Back", throwIfNotFound: true);
        m_UImap_Enter = m_UImap.FindAction("Enter", throwIfNotFound: true);
        m_UImap_Exit = m_UImap.FindAction("Exit", throwIfNotFound: true);
        m_UImap_Left = m_UImap.FindAction("Left", throwIfNotFound: true);
        m_UImap_Right = m_UImap.FindAction("Right", throwIfNotFound: true);
    }

    ~@PlayerControls()
    {
        UnityEngine.Debug.Assert(!m_MapNormale.enabled, "This will cause a leak and performance issues, PlayerControls.MapNormale.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UImap.enabled, "This will cause a leak and performance issues, PlayerControls.UImap.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MapNormale
    private readonly InputActionMap m_MapNormale;
    private List<IMapNormaleActions> m_MapNormaleActionsCallbackInterfaces = new List<IMapNormaleActions>();
    private readonly InputAction m_MapNormale_Mouvement;
    private readonly InputAction m_MapNormale_Regarder;
    private readonly InputAction m_MapNormale_Saut;
    private readonly InputAction m_MapNormale_Sprint;
    private readonly InputAction m_MapNormale_LightAttack;
    private readonly InputAction m_MapNormale_HeavyAttack;
    private readonly InputAction m_MapNormale_Crouch;
    private readonly InputAction m_MapNormale_Unsheath;
    private readonly InputAction m_MapNormale_LockOn;
    private readonly InputAction m_MapNormale_Guarding;
    private readonly InputAction m_MapNormale_Roll;
    private readonly InputAction m_MapNormale_Interact;
    private readonly InputAction m_MapNormale_Heal;
    private readonly InputAction m_MapNormale_LockOnIndexR2;
    private readonly InputAction m_MapNormale_DebugTool;
    private readonly InputAction m_MapNormale_SwitchKatana;
    public struct MapNormaleActions
    {
        private @PlayerControls m_Wrapper;
        public MapNormaleActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Mouvement => m_Wrapper.m_MapNormale_Mouvement;
        public InputAction @Regarder => m_Wrapper.m_MapNormale_Regarder;
        public InputAction @Saut => m_Wrapper.m_MapNormale_Saut;
        public InputAction @Sprint => m_Wrapper.m_MapNormale_Sprint;
        public InputAction @LightAttack => m_Wrapper.m_MapNormale_LightAttack;
        public InputAction @HeavyAttack => m_Wrapper.m_MapNormale_HeavyAttack;
        public InputAction @Crouch => m_Wrapper.m_MapNormale_Crouch;
        public InputAction @Unsheath => m_Wrapper.m_MapNormale_Unsheath;
        public InputAction @LockOn => m_Wrapper.m_MapNormale_LockOn;
        public InputAction @Guarding => m_Wrapper.m_MapNormale_Guarding;
        public InputAction @Roll => m_Wrapper.m_MapNormale_Roll;
        public InputAction @Interact => m_Wrapper.m_MapNormale_Interact;
        public InputAction @Heal => m_Wrapper.m_MapNormale_Heal;
        public InputAction @LockOnIndexR2 => m_Wrapper.m_MapNormale_LockOnIndexR2;
        public InputAction @DebugTool => m_Wrapper.m_MapNormale_DebugTool;
        public InputAction @SwitchKatana => m_Wrapper.m_MapNormale_SwitchKatana;
        public InputActionMap Get() { return m_Wrapper.m_MapNormale; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MapNormaleActions set) { return set.Get(); }
        public void AddCallbacks(IMapNormaleActions instance)
        {
            if (instance == null || m_Wrapper.m_MapNormaleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MapNormaleActionsCallbackInterfaces.Add(instance);
            @Mouvement.started += instance.OnMouvement;
            @Mouvement.performed += instance.OnMouvement;
            @Mouvement.canceled += instance.OnMouvement;
            @Regarder.started += instance.OnRegarder;
            @Regarder.performed += instance.OnRegarder;
            @Regarder.canceled += instance.OnRegarder;
            @Saut.started += instance.OnSaut;
            @Saut.performed += instance.OnSaut;
            @Saut.canceled += instance.OnSaut;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @LightAttack.started += instance.OnLightAttack;
            @LightAttack.performed += instance.OnLightAttack;
            @LightAttack.canceled += instance.OnLightAttack;
            @HeavyAttack.started += instance.OnHeavyAttack;
            @HeavyAttack.performed += instance.OnHeavyAttack;
            @HeavyAttack.canceled += instance.OnHeavyAttack;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Unsheath.started += instance.OnUnsheath;
            @Unsheath.performed += instance.OnUnsheath;
            @Unsheath.canceled += instance.OnUnsheath;
            @LockOn.started += instance.OnLockOn;
            @LockOn.performed += instance.OnLockOn;
            @LockOn.canceled += instance.OnLockOn;
            @Guarding.started += instance.OnGuarding;
            @Guarding.performed += instance.OnGuarding;
            @Guarding.canceled += instance.OnGuarding;
            @Roll.started += instance.OnRoll;
            @Roll.performed += instance.OnRoll;
            @Roll.canceled += instance.OnRoll;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Heal.started += instance.OnHeal;
            @Heal.performed += instance.OnHeal;
            @Heal.canceled += instance.OnHeal;
            @LockOnIndexR2.started += instance.OnLockOnIndexR2;
            @LockOnIndexR2.performed += instance.OnLockOnIndexR2;
            @LockOnIndexR2.canceled += instance.OnLockOnIndexR2;
            @DebugTool.started += instance.OnDebugTool;
            @DebugTool.performed += instance.OnDebugTool;
            @DebugTool.canceled += instance.OnDebugTool;
            @SwitchKatana.started += instance.OnSwitchKatana;
            @SwitchKatana.performed += instance.OnSwitchKatana;
            @SwitchKatana.canceled += instance.OnSwitchKatana;
        }

        private void UnregisterCallbacks(IMapNormaleActions instance)
        {
            @Mouvement.started -= instance.OnMouvement;
            @Mouvement.performed -= instance.OnMouvement;
            @Mouvement.canceled -= instance.OnMouvement;
            @Regarder.started -= instance.OnRegarder;
            @Regarder.performed -= instance.OnRegarder;
            @Regarder.canceled -= instance.OnRegarder;
            @Saut.started -= instance.OnSaut;
            @Saut.performed -= instance.OnSaut;
            @Saut.canceled -= instance.OnSaut;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @LightAttack.started -= instance.OnLightAttack;
            @LightAttack.performed -= instance.OnLightAttack;
            @LightAttack.canceled -= instance.OnLightAttack;
            @HeavyAttack.started -= instance.OnHeavyAttack;
            @HeavyAttack.performed -= instance.OnHeavyAttack;
            @HeavyAttack.canceled -= instance.OnHeavyAttack;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Unsheath.started -= instance.OnUnsheath;
            @Unsheath.performed -= instance.OnUnsheath;
            @Unsheath.canceled -= instance.OnUnsheath;
            @LockOn.started -= instance.OnLockOn;
            @LockOn.performed -= instance.OnLockOn;
            @LockOn.canceled -= instance.OnLockOn;
            @Guarding.started -= instance.OnGuarding;
            @Guarding.performed -= instance.OnGuarding;
            @Guarding.canceled -= instance.OnGuarding;
            @Roll.started -= instance.OnRoll;
            @Roll.performed -= instance.OnRoll;
            @Roll.canceled -= instance.OnRoll;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Heal.started -= instance.OnHeal;
            @Heal.performed -= instance.OnHeal;
            @Heal.canceled -= instance.OnHeal;
            @LockOnIndexR2.started -= instance.OnLockOnIndexR2;
            @LockOnIndexR2.performed -= instance.OnLockOnIndexR2;
            @LockOnIndexR2.canceled -= instance.OnLockOnIndexR2;
            @DebugTool.started -= instance.OnDebugTool;
            @DebugTool.performed -= instance.OnDebugTool;
            @DebugTool.canceled -= instance.OnDebugTool;
            @SwitchKatana.started -= instance.OnSwitchKatana;
            @SwitchKatana.performed -= instance.OnSwitchKatana;
            @SwitchKatana.canceled -= instance.OnSwitchKatana;
        }

        public void RemoveCallbacks(IMapNormaleActions instance)
        {
            if (m_Wrapper.m_MapNormaleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMapNormaleActions instance)
        {
            foreach (var item in m_Wrapper.m_MapNormaleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MapNormaleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MapNormaleActions @MapNormale => new MapNormaleActions(this);

    // UImap
    private readonly InputActionMap m_UImap;
    private List<IUImapActions> m_UImapActionsCallbackInterfaces = new List<IUImapActions>();
    private readonly InputAction m_UImap_Up;
    private readonly InputAction m_UImap_Down;
    private readonly InputAction m_UImap_Back;
    private readonly InputAction m_UImap_Enter;
    private readonly InputAction m_UImap_Exit;
    private readonly InputAction m_UImap_Left;
    private readonly InputAction m_UImap_Right;
    public struct UImapActions
    {
        private @PlayerControls m_Wrapper;
        public UImapActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Up => m_Wrapper.m_UImap_Up;
        public InputAction @Down => m_Wrapper.m_UImap_Down;
        public InputAction @Back => m_Wrapper.m_UImap_Back;
        public InputAction @Enter => m_Wrapper.m_UImap_Enter;
        public InputAction @Exit => m_Wrapper.m_UImap_Exit;
        public InputAction @Left => m_Wrapper.m_UImap_Left;
        public InputAction @Right => m_Wrapper.m_UImap_Right;
        public InputActionMap Get() { return m_Wrapper.m_UImap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UImapActions set) { return set.Get(); }
        public void AddCallbacks(IUImapActions instance)
        {
            if (instance == null || m_Wrapper.m_UImapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UImapActionsCallbackInterfaces.Add(instance);
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
            @Down.started += instance.OnDown;
            @Down.performed += instance.OnDown;
            @Down.canceled += instance.OnDown;
            @Back.started += instance.OnBack;
            @Back.performed += instance.OnBack;
            @Back.canceled += instance.OnBack;
            @Enter.started += instance.OnEnter;
            @Enter.performed += instance.OnEnter;
            @Enter.canceled += instance.OnEnter;
            @Exit.started += instance.OnExit;
            @Exit.performed += instance.OnExit;
            @Exit.canceled += instance.OnExit;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
        }

        private void UnregisterCallbacks(IUImapActions instance)
        {
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
            @Down.started -= instance.OnDown;
            @Down.performed -= instance.OnDown;
            @Down.canceled -= instance.OnDown;
            @Back.started -= instance.OnBack;
            @Back.performed -= instance.OnBack;
            @Back.canceled -= instance.OnBack;
            @Enter.started -= instance.OnEnter;
            @Enter.performed -= instance.OnEnter;
            @Enter.canceled -= instance.OnEnter;
            @Exit.started -= instance.OnExit;
            @Exit.performed -= instance.OnExit;
            @Exit.canceled -= instance.OnExit;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
        }

        public void RemoveCallbacks(IUImapActions instance)
        {
            if (m_Wrapper.m_UImapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUImapActions instance)
        {
            foreach (var item in m_Wrapper.m_UImapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UImapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UImapActions @UImap => new UImapActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_ControllerSchemeIndex = -1;
    public InputControlScheme ControllerScheme
    {
        get
        {
            if (m_ControllerSchemeIndex == -1) m_ControllerSchemeIndex = asset.FindControlSchemeIndex("Controller");
            return asset.controlSchemes[m_ControllerSchemeIndex];
        }
    }
    public interface IMapNormaleActions
    {
        void OnMouvement(InputAction.CallbackContext context);
        void OnRegarder(InputAction.CallbackContext context);
        void OnSaut(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnLightAttack(InputAction.CallbackContext context);
        void OnHeavyAttack(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnUnsheath(InputAction.CallbackContext context);
        void OnLockOn(InputAction.CallbackContext context);
        void OnGuarding(InputAction.CallbackContext context);
        void OnRoll(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnHeal(InputAction.CallbackContext context);
        void OnLockOnIndexR2(InputAction.CallbackContext context);
        void OnDebugTool(InputAction.CallbackContext context);
        void OnSwitchKatana(InputAction.CallbackContext context);
    }
    public interface IUImapActions
    {
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
        void OnEnter(InputAction.CallbackContext context);
        void OnExit(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
    }
}
